export const classNameTransformer = (className: string) => {
  return className
    .replace(/\|/g, '\\|')
    .replace(/,/g, '\\,')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/\?/g, '\\?')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\[/g, '\\[')
    .replace(/\]/g, '\\]')
    .replace(/\//g, '\\/')
    .replace(/:/g, '\\:')
    .replace(/;/g, '\\;')
    .replace(/@/g, '\\@')
    .replace(/#/g, '\\#')
    .replace(/'/g, "\\'")
    .replace(/"/g, `\\"`)
    .replace(/%/g, `\\%`)
    .replace(/\+/g, `\\+`)
    .replace(/>/g, `\\>`)
    .replace(/!/g, `\\!`)
    .replace(/`/g, '\\`')
    .replace(/\.\d/g, value => '\\' + value)
    .replace(/\^/g, '\\^');
};
